FROM gradle:7.2.0-jdk11 AS builder

ARG ROOT_DIR

WORKDIR /app
COPY ${ROOT_DIR} .
RUN bash ./gradlew build 

FROM openjdk

WORKDIR /app
EXPOSE ${PORT}
COPY --from=builder /app/build/libs/ticketing-1.0.0.jar .
CMD [ "java", "-Dserver.port=$PORT", "-jar", "ticketing-1.0.0.jar" ]