version: '3.8'

services:
  web:
    container_name: hack-it-frontend
    image: hack-it-frontend
    build: 
      context: .
      dockerfile: Dockerfile.web
      args:
        ROOT_DIR: ${CLIENT_WEB_DIR}
    ports:
      - "80:80"
  api:
    container_name: hack-it-backend
    image: hack-it-backend 
    build:
      context: .
      dockerfile: Dockerfile.ticketing.service
      args:
        ROOT_DIR: ${TICKETING_SERVICE_DIR}
    ports:
      - "8080:8080"
 