FROM node:alpine AS builder

WORKDIR /app

ARG ROOT_DIR

COPY ${ROOT_DIR}/package*.json .
RUN npm install

COPY ${ROOT_DIR} .
RUN npm run build

FROM nginx 

WORKDIR /app

EXPOSE 80

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/build /usr/share/nginx/html

